### PR TITLE
Fix: Remove unwanted underline from Sign In button on desktop

### LINKED ISSUE #968: Unwanted extra border on the Sign in button on desktop
What's up with this guy's bottom edge? The button shows up nicely on mobile.

Image

Happens when the sign page is active, see: https://falling-fruit-web.pages.dev/auth/sign_in?fromPage=%2Fabout%2Fproject.

### PR DESCRIPTION
**Pull request by Pratik00531**
## Description
Fixes the unwanted orange underline appearing on the Sign In button on desktop view.

## Changes
- Added specific styles for `.signin` and `.signup` NavLink elements
- Hides the `::before` pseudo-element that creates the underline
- Prevents underline from showing on both hover and active states

## Fixes
Closes #968

## Screenshots
Before: (The issue screenshot from #968)
After: Sign In button now appears without the bottom border
image
## Testing
Tested on desktop view - Sign In button no longer shows orange underline.

### CODE REVIEW

File: src/components/desktop/Header.js [hunk 1]
```diff
@@ -285,15 +302,15 @@ const UserMenu = () => {
               }
               isMatch={isAccountPage}
             >
-              <NavLink to="/account/edit" activeClassName="active">
+              <MenuItem to="/account/edit" activeClassName="active">
```
Comment (wbazant) [inline src/components/desktop/Header.js]: This is as I intended, thank you for implementing the request!
